// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveRequest(arg1) {
  return window['go']['main']['App']['ApproveRequest'](arg1);
}

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function CreateNewProject(arg1) {
  return window['go']['main']['App']['CreateNewProject'](arg1);
}

export function FetchSettings(arg1) {
  return window['go']['main']['App']['FetchSettings'](arg1);
}

export function GetAllRequests(arg1) {
  return window['go']['main']['App']['GetAllRequests'](arg1);
}

export function GetCurrentVersion(arg1) {
  return window['go']['main']['App']['GetCurrentVersion'](arg1);
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetTrafficData(arg1) {
  return window['go']['main']['App']['GetTrafficData'](arg1);
}

export function HandleProxyRequest(arg1) {
  return window['go']['main']['App']['HandleProxyRequest'](arg1);
}

export function HandleProxyResponse(arg1, arg2) {
  return window['go']['main']['App']['HandleProxyResponse'](arg1, arg2);
}

export function SwitchProject(arg1) {
  return window['go']['main']['App']['SwitchProject'](arg1);
}

export function ToggleInterception() {
  return window['go']['main']['App']['ToggleInterception']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
