// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';

export function ApproveRequest(arg1:{[key: string]: any}):Promise<void>;

export function CheckForUpdates(arg1:Array<any>):Promise<void>;

export function CreateNewProject(arg1:Array<any>):Promise<void>;

export function FetchSettings(arg1:Array<any>):Promise<void>;

export function GetAllRequests(arg1:Array<any>):Promise<void>;

export function GetCurrentVersion(arg1:Array<any>):Promise<void>;

export function GetRecentLogs(arg1:Array<any>):Promise<void>;

export function GetTrafficData(arg1:Array<any>):Promise<void>;

export function HandleProxyRequest(arg1:http.Request):Promise<void>;

export function HandleProxyResponse(arg1:http.Request,arg2:http.Response):Promise<void>;

export function SwitchProject(arg1:Array<any>):Promise<void>;

export function ToggleInterception():Promise<void>;

export function UpdateSettings(arg1:Array<any>):Promise<void>;
